/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smart_expense_tracker;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Report extends javax.swing.JFrame {

    Connection conn = Connect.Connecttodb();
    PreparedStatement pst;
    ResultSet rs;
    
    /**
     * Creates new form report
     */
    public Report() {
        initComponents();
        loaddetails();
    }

    
   public final void loaddetails() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Date");
    model.addColumn("Income");
    model.addColumn("Expense");
    model.addColumn("Profit/Loss");

    String sql = "SELECT date AS EntryDate, " +
                 "SUM(CASE WHEN Type = 'Income' AND amount REGEXP '^[0-9]+(\\.[0-9]+)?$' " +
                 "THEN CAST(amount AS DECIMAL(10, 2)) ELSE 0 END) AS TotalIncome, " +
                 "SUM(CASE WHEN Type = 'Expense' AND amount REGEXP '^[0-9]+(\\.[0-9]+)?$' " +
                 "THEN CAST(amount AS DECIMAL(10, 2)) ELSE 0 END) AS TotalExpense, " +
                 "SUM(CASE WHEN Type = 'Income' AND amount REGEXP '^[0-9]+(\\.[0-9]+)?$' " +
                 "THEN CAST(amount AS DECIMAL(10, 2)) ELSE 0 END) - " +
                 "SUM(CASE WHEN Type = 'Expense' AND amount REGEXP '^[0-9]+(\\.[0-9]+)?$' " +
                 "THEN CAST(amount AS DECIMAL(10, 2)) ELSE 0 END) AS ProfitLoss " +
                 "FROM ( " +
                 "  SELECT date, amount, 'Income' AS Type FROM income WHERE USERNAME = ? " +
                 "  UNION ALL " +
                 "  SELECT date, amount, 'Expense' AS Type FROM expense WHERE USERNAME = ? " +
                 ") AS Combined " +
                 "GROUP BY EntryDate " +
                 "ORDER BY EntryDate;";

    try {
        // Get username from shared data
        String username = LogIn.SharedData.username;
        JOptionPane.showMessageDialog(rootPane, username);
        // Ensure username is not null or empty
        if (username == null || username.trim().isEmpty()) {
            System.out.println("Invalid or missing username.");
            return;
        }

        // Prepare and execute query
        pst = conn.prepareStatement(sql);
        pst.setString(1, username);
        pst.setString(2, username);
        rs = pst.executeQuery();

        // Process the result set
        int rowCount = 0;
        while (rs.next()) {
            String entryDate = rs.getString("EntryDate");
            String totalIncome = rs.getString("TotalIncome");
            String totalExpense = rs.getString("TotalExpense");
            String profitLoss = rs.getString("ProfitLoss");

            // Debug output to console
//            System.out.println("Row fetched - Date: " + entryDate + ", Income: " + totalIncome + 
//                               ", Expense: " + totalExpense + ", Profit/Loss: " + profitLoss);

            model.addRow(new Object[]{entryDate, totalIncome, totalExpense, profitLoss});
            rowCount++;
        }

        // Debug log for row count
//        System.out.println("Total rows fetched: " + rowCount);

        // Set table model
        report_table.setModel(model);

        // Refresh table
        report_table.repaint();
        report_table.revalidate();

        // Debug: Log if no rows are returned
        if (rowCount == 0) {
            System.out.println("No data available for the user: " + username);
        }

    } catch (SQLException ex) {
        // Log exceptions
        ex.printStackTrace();
        Logger.getLogger(Income.class.getName()).log(Level.SEVERE, null, ex);
    }
}



    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        report_table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(210, 100));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1070, 780));
        setResizable(false);
        setSize(new java.awt.Dimension(1070, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        report_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Income", "Expense", "Profit/ Loss"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(report_table);
        if (report_table.getColumnModel().getColumnCount() > 0) {
            report_table.getColumnModel().getColumn(0).setResizable(false);
            report_table.getColumnModel().getColumn(1).setResizable(false);
            report_table.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1070, 740));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 50, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable report_table;
    // End of variables declaration//GEN-END:variables
}
